sudo: required

services:
- docker

install: true

script:
- docker build -t up2university/learninglocker-mongo:"$TRAVIS_BRANCH" mongo
- docker build -t up2university/learninglocker:"$TRAVIS_BRANCH" learninglocker
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
    docker push up2university/learninglocker-mongo:"$TRAVIS_BRANCH";
    docker push up2university/learninglocker:"$TRAVIS_BRANCH";
    fi

