learninglocker:
  image: slidewiki/learninglocker
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - VIRTUAL_HOST=learninglocker.experimental.slidewiki.org
    - LETSENCRYPT_HOST=learninglocker.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - APP_URL=learninglocker.experimental.slidewiki.org
    - LEARNINGLOCKER_DB_HOST=mongodb
    - LEARNINGLOCKER_DB_NAME=learninglocker
    - APP_SECRET_KEY=5825195449557a9f407bf4a0c28f97a6
