version: '2'

services:
    mongo:
        build:
             context: mongo
        env_file:
             - .env
        ports:
             - "27017:27017"
             - "28017:28017"
        volumes:
             - /data/learninglocker-mongo:/data/db
    learninglocker:
        build: .
        restart: always
        links:
            - mongo
        ports:
            - "80:80"
            - "81:81"
        env_file:
            - .env
